# Generated by Django 4.1.5 on 2023-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=2, max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
