# Generated by Django 4.1.5 on 2023-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Cover image'),
        ),
    ]
