# Generated by Django 4.1.5 on 2023-02-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_title_favorite_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
