# Generated by Django 4.1.5 on 2023-02-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_favorite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.AddField(
            model_name='favorite',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
